spring.datasource.url=jdbc:postgresql://dpg-d7fj62jeo5us73euhvtg-a:5432/clothing_db_uffg
spring.datasource.username=clothing_db_uffg_user
spring.datasource.password=5EIZw32qCSNb8rIE03Nky5UqZkudR6Ng

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}